server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
    active: ${ENVIRONMENT:local}
  jpa:
    hibernate:
        ddl-auto: update #or - create, create-drop, validate, update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
tangocard:
  accountIdentifier: main-account
  customerIdentifier: main-customer
---

spring:
  profiles: cloud
  datasource:
      url: jdbc:postgresql://${DATABASE_CONNECTION_STRING}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
tangocard:
  baseUrl: ${TANGO_BASE_URL}
  username: ${TANGO_USERNAME}
  password: ${TANGO_PASSWORD}

cloud:
  aws:
    region: ${S3_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

---

spring:
    profiles: local
    datasource:
        url: jdbc:postgresql://localhost:5432/majorperk